### ISSUE TITLE
请问如何通过as调试输出日志信息

### ISSUE THREAD

**Issue by bike3097a** [dqzg12300/MikManager#2]
如题所示

**Comment by dqzg12300** [comment]
logcat日志搜索mikrom

**Comment by bike3097a** [comment]
我测试了 没有dump文件夹

**Comment by bike3097a** [comment]
难道必须连接电脑 通过 logcat 来脱壳吗？直接设置不行吗？

**Comment by dqzg12300** [comment]
不需要通过logcat来脱壳。直接设置就可以了。目录是 /sdcard/Android/data//files/dump。logcat主要是用来看是否正常在执行脱壳中。

**Comment by bike3097a** [comment]
没有哦，路径对的，图片我已经发到你网易邮箱里了。

**Comment by dqzg12300** [comment]
mikmanager要使用对应mikrom v1.0.1版本。去下载一下最新的就行了。

**Comment by bike3097a** [comment]
![Screenshot_20220622_210356_com android packageinstaller](https://user-images.githubusercontent.com/72074704/175036105-cf34a5d0-46d3-4718-be27-d2566be8daf5.jpg)
安装提示这个错误，我在mikrom上也是无法安装。

**Comment by bike3097a** [comment]
![-52675f50768f1d4d](https://user-images.githubusercontent.com/72074704/175040214-fce9fdf5-6dae-4968-b3de-96e9f3650946.jpg)
这个错误，啥情况呀，是安装包的问题吗？
