### ISSUE TITLE
奇了怪了，我弄到本地自己编译报错

### ISSUE THREAD

**Issue by bike3097a** [dqzg12300/MikManager#4]
如题跑，编译失败。

**Comment by dqzg12300** [comment]
你设置编译debug的试试看。

**Comment by bike3097a** [comment]
默认就是debug哦 没有用

**Comment by bike3097a** [comment]
android studio是最新版

**Comment by dqzg12300** [comment]
可能是jdk版本的问题吧。你试试用jdk1.8的试试看

**Comment by bike3097a** [comment]
我的就是jdk1.8

**Comment by bike3097a** [comment]
这样吧  反正我是fork你的项目 git到本地编译报错的

**Comment by dqzg12300** [comment]
你是win还是ubuntu？我有空测试下看看

**Comment by bike3097a** [comment]
我的是win下的，在家和公司都不行，windows10系统

**Comment by dqzg12300** [comment]
好的。你先用release的。win的编译问题我周一的时候看下。

**Comment by bike3097a** [comment]
好的，下一版后我在试试。

**Comment by bike3097a** [comment]
解决了吗。

**Comment by dqzg12300** [comment]
![image](https://user-images.githubusercontent.com/19391415/175951925-48782a63-bc0e-48c5-be23-038868ac7543.png)
并没有碰到你说的问题。我的虚拟机重头搞环境，就是装下android studio。然后git下载项目。直接编译就行了。有可能是你的android studio版本比较老把

**Comment by bike3097a** [comment]
> 

不应该呀，最近才更新的，一会我在测试下

**Comment by bike3097a** [comment]
我的android studio 版本是 2021.1 patch 1

**Comment by bike3097a** [comment]
Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 19, 2022
Runtime version: 11.0.12+7-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.genymotion.idea (1.0.9), org.jetbrains.kotlin (212-1.7.0-release-281-AS5457.46), org.intellij.plugins.markdown (212.5457.16)

**Comment by bike3097a** [comment]
不好意思呀，原来是gradle版本的问题，默认就好了

**Comment by bike3097a** [comment]
Execution failed for task ':app:lintVitalRelease'.
> Lint found fatal errors while assembling a release target.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by bike3097a** [comment]
编译测试版可以的
