### ISSUE TITLE
数字壳脱出来的activity onCreate 是native的，是不支持的吗？

### ISSUE THREAD

**Issue by liang530** [dqzg12300/MikManager#7]
你好，首先谢谢你提供此工具。

我在脱数字壳时，脱出来的dex中activity是下面这个样子，MikRom的修复功能是不支持的吗？
`  public native void onCreate(Bundle bundle);

    public native void onRequestPermissionsResult(int i, String[] strArr, int[] iArr);

    static {
        StubApp.interface11(11257);
    }`

**Comment by dqzg12300** [comment]
这种应该是vmp壳，非抽取的。vmp壳一般没办法做到自动脱壳，只能自行分析，或者针对某个厂商的vmp壳做映射表解析。

**Comment by liang530** [comment]
嗯嗯，了解了下vmp的原理，好像目前是不能自动脱壳。
谢谢解答。
